default_title: Asian Star Consulting
default_keywords:  Китай, поиск поставщиков, китайские производители, логистика, доставка
default_description: Основные направления нашей деятельности поиск поставщиков и товаров в Китае, взаимодействие с китайскими производителями, выполнение логистических операций в полном объёме.
