development:
  adapter: postgresql
  database: brettdb_develpment
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: brettdb_test
  pool: 5
  timeout: 5000
production:
  adapter: postgresql
  database: brettdb_production
  pool: 5
  timeout: 5000
